### ISSUE TITLE
What wearable devices to use for vital data detection and transmission?

### ISSUE THREAD

**Issue by BillBrazerZhang** [WeibelLab-Teaching/CSE218_Fa19_HoloVitality#4]
Hi all, based on today's meeting, we decided to use TCP for data transmission between clients(wearables and HoloLens) and our server on PC. The reason we choose TCP(web socket) instead of BlueTooth is that it supports multiple clients connected to the server instead of point-to-point communications. To achieve that, we have to get wearable devices with the network card. Right now we have two device options:

1.  Use smartphones attached to the human's chest for heart rate detection, which is a substitute for wearables. The advantage to do so is that we already know much on this platform and it's easy for data transmission from smartphones to the server. The disadvantage is that it's not likely to track vital signs in the real workout situation.
2. Use wearables with the network card(i.e. can be connected to WiFi or Hotspot, etc). The advantage is that it's more close to real application. The challenge is that we don't know much about which smartwatch has better API for data transmission to server, and we also need to buy certain devices.

So let's talk about which option is better. If you have certain documents about certain wearables and the available APIs, please feel free to share them in the followups.

**Comment by Joyfal** [comment]
According to our research, fitbit seems to be the best device that accommandates our needs

**Comment by Joyfal** [comment]
However, as we gathered more information about fitbit SDK, we learned that there is no easy way to gather live data from fitbit other than writing an app on fitbit itself. So we decided to use an Android app on phone that tracks heart rate using accelerometer SCG.
